// Phase 49 — Public AI-tool exposure guard.
//
// Run: node test/public-ai-exposure.test.js
//
// The owner does not want the public production site to disclose that it was
// built with AI coding tools. This checks two things: (1) the firebase.json
// hosting `ignore` list still excludes every internal/dev-only path, so a
// hosting deploy never ships docs/ai/, test/, .claude/, etc.; (2) public HTML
// (root pages + all locale mirrors) contains none of a small set of specific
// disclosure terms. Deliberately narrow term list and word-boundary matching
// to avoid flagging harmless substrings inside unrelated words or third-party
// library identifiers (e.g. a CSS icon class name).

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

let passed = 0, failed = 0;
function section(t) { console.log(`\n# ${t}`); }
function test(name, fn) {
  try { fn(); passed++; console.log(`  ok  - ${name}`); }
  catch (e) { failed++; console.log(`  FAIL - ${name}`); console.log('        ' + e.message); process.exitCode = 1; }
}
function read(p) { return fs.readFileSync(p, 'utf8'); }

section('Case A — firebase.json hosting ignore list excludes every internal/dev-only path');
{
  const fb = JSON.parse(read('firebase.json'));
  const ignore = fb.hosting.ignore || [];
  test('docs/** (docs/ai/, docs/business/ — internal strategy/continuity docs) is excluded from hosting', () => {
    assert.ok(ignore.includes('docs/**'), 'docs/** missing from firebase.json hosting.ignore');
  });
  test('test/** is excluded from hosting', () => {
    assert.ok(ignore.includes('test/**'), 'test/** missing from firebase.json hosting.ignore');
  });
  test('.claude/** and dotfiles/dot-directories are excluded from hosting', () => {
    assert.ok(ignore.includes('.claude/**'), '.claude/** missing from firebase.json hosting.ignore');
    assert.ok(ignore.includes('**/.*') && ignore.includes('**/.*/**'), 'generic dotfile/dot-directory ignore rules missing');
  });
  test('firestore.rules/functions/** are excluded from a hosting deploy (they deploy via their own separate target)', () => {
    assert.ok(ignore.includes('firestore.rules'), 'firestore.rules missing from firebase.json hosting.ignore');
    assert.ok(ignore.includes('functions/**'), 'functions/** missing from firebase.json hosting.ignore');
  });
}

section('Case B — public HTML contains no AI-tool disclosure terms');
{
  // Deliberately specific, case-sensitive-ish terms with word boundaries —
  // broad/lowercase terms like "gpt" or "prompt" alone would false-positive
  // on unrelated content (e.g. a font icon class), so this checks only
  // terms with essentially zero legitimate false-positive surface for a
  // Maldives guesthouse site.
  const TERMS = [
    /\bClaude\b/, /\bAnthropic\b/, /\bChatGPT\b/, /\bOpenAI\b/,
    /\bAI[- ]generated\b/i, /\bAI[- ]written\b/i, /\bgenerated by AI\b/i,
    /\blanguage model\b/i, /\bLLM\b/,
  ];
  const SKIP_FILES = new Set(['vilu-unified.html', 'vilu-agency-portal.html']); // internal/login-gated, not public pages

  function publicHtmlFiles() {
    const out = [];
    const rootEntries = fs.readdirSync('.', { withFileTypes: true });
    for (const e of rootEntries) {
      if (e.isFile() && e.name.endsWith('.html') && !SKIP_FILES.has(e.name)) out.push(e.name);
    }
    const localeDirs = ['ar', 'cs', 'de', 'es', 'fr', 'it', 'ja', 'ko', 'ru', 'sk', 'zh'];
    for (const loc of localeDirs) {
      if (!fs.existsSync(loc)) continue;
      for (const e of fs.readdirSync(loc, { withFileTypes: true })) {
        if (e.isFile() && e.name.endsWith('.html')) out.push(path.join(loc, e.name));
      }
    }
    return out;
  }

  test('no public HTML file (root pages + all locale mirrors) contains an AI-tool disclosure term', () => {
    const files = publicHtmlFiles();
    assert.ok(files.length > 50, `expected many public HTML files, found only ${files.length} — file discovery may be broken`);
    const hits = [];
    for (const f of files) {
      const html = read(f);
      for (const re of TERMS) {
        if (re.test(html)) hits.push(`${f}: matched ${re}`);
      }
    }
    assert.equal(hits.length, 0, 'AI-tool disclosure term(s) found:\n' + hits.join('\n'));
  });
}

section('Summary');
console.log(`\n${passed}/${passed + failed} public-ai-exposure assertions passed`);
if (failed > 0) process.exitCode = 1;
