/// <reference types="expo/types" />

// This file is auto-generated by `expo start`/`expo prebuild` in a real
// checkout; a static stub is committed here only so `tsc --noEmit` has a
// valid entry to include before that generation has run.
